import java.util.Scanner;

interface Payment {
    void processPayment(double amount);
}

class CreditCardPayment implements Payment {
    @Override
    public void processPayment(double amount)
    {
        System.out.println("Processing Credit card payment of $ " + amount);
        System.out.println("Payment success. Confirmed payment by Credit card.");
    }
}

class PayPalPayment implements Payment {
    @Override
    public void processPayment(double amount) {
        System.out.println("Processing PayPal payment of $" + amount);
        System.out.println("Payment Successful: Transaction ID generated by PayPal.");
    }
}

class CryptoPayment implements Payment {
    @Override
    public void processPayment(double amount) {
        System.out.println("Processing Cryptocurrency payment of $" + amount);
        System.out.println("Payment Successful: Block confirmed on the Blockchain.");
    }
}

// factory
class PaymentFactory {
    public Payment getPaymentMethod(String type) {
        if (type == null)
            return null;

        if (type.equalsIgnoreCase("CREDIT CARD")) {
            return new CreditCardPayment();
        } else if (type.equalsIgnoreCase("PAYPAL")) {
            return new PayPalPayment();
        } else if (type.equalsIgnoreCase("CRYPTO")) {
            return new CryptoPayment();
        }

        return null;
    }
}

public class Main{
    public static void main(String[] args) {
        PaymentFactory ft= new PaymentFactory();
        Scanner sc = new Scanner(System.in);
        System.out.println("choose your preferred method: ");
        String choice = sc.nextLine();
        Payment userPayment= ft.getPaymentMethod(choice);
        if(userPayment!=null) userPayment.processPayment(2500.00);
        else System.out.println("invalid payment method selected");
        sc.close();
    }
}